// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEbwP-ssMOEQAvdhyXmn_lK-nN35GAM8',
    appId: '1:709676975315:web:63efcf98d9f3949f8d4026',
    messagingSenderId: '709676975315',
    projectId: 'mim-1c1c9',
    authDomain: 'mim-1c1c9.firebaseapp.com',
    storageBucket: 'mim-1c1c9.appspot.com',
    measurementId: 'G-Y9F827M1YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4XeAGwMAlFdQVZwDT5N5azaaWk-jua8',
    appId: '1:709676975315:android:fe026fd1d1bbc9ab8d4026',
    messagingSenderId: '709676975315',
    projectId: 'mim-1c1c9',
    storageBucket: 'mim-1c1c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABK_R4cHpVVma3zi1eQfeZnt_LYcatmqg',
    appId: '1:709676975315:ios:c3d4726ec88b59618d4026',
    messagingSenderId: '709676975315',
    projectId: 'mim-1c1c9',
    storageBucket: 'mim-1c1c9.appspot.com',
    iosBundleId: 'com.example.minigram',
  );

}